### ISSUE TITLE
Cannot build on Ubuntu 18.04.2

### ISSUE THREAD

**Issue by naokikob** [seahorn/seahorn#405]
Hi, I could not install Seahorn on Ubuntu 18.04.2 (on top of Windows WSL),
and am wondering whether cmake files are outdated.

I followed the six steps procedure in README.md, but in the 3rd step, I get:

```
svn: E170011: Repository moved temporarily to 'https://llvm.org/svn/llvm-project/llvm/tags/RELEASE_500/final'
CMakeFiles/llvm.dir/build.make:90: recipe for target 'llvm-prefix/src/llvm-stamp/llvm-download' 
```

I have managed to pass the 3rd step by editing CMakeLists.txt to download LLVM 5.0.0 from https://github.com/llvm/llvm-project.git.

But then in the 6th step, I got another error:
```
In file included from .../clam/lib/Clam/CfgBuilder.cc:57:0:
.../clam/lib/Clam/CfgBuilderMemRegions.hh:8:10: fatal error: seadsa/Graph.hh: No such file or directory
 #include "seadsa/Graph.hh"
```
Graph.hh is actually in the directory sea-dsa/include/sea_dsa/

I tried creating a symbolic link from seadsa to sea_dsa, but then I encountered the following error.

```
[ 34%] Building CXX object clam/lib/Clam/CMakeFiles/ClamAnalysis.dir/CfgBuilder.cc.o
.../clam/lib/Clam/CfgBuilder.cc: In member function 'void clam::CrabIntraBlockBuilder::StoreIntoSingletonMem(llvm::StoreInst&, clam::var_t, clam::crab_lit_ref_t, clam::Region)':
.../clam/lib/Clam/CfgBuilder.cc:2267:61: error: request for member 'getFixedSize' in '((clam::CrabIntraBlockBuilder*)this)->clam::CrabIntraBlockBuilder::m_dl->llvm::DataLayout::getTypeAllocSize(ty)', which is of non-class type 'uint64_t {aka long unsigned int}'
                                  m_dl->getTypeAllocSize(ty).getFixedSize(),
                                                             ^~~~~~~~~~~~
```

**Comment by agurfinkel** [comment]
please use `dev10` branch. We are in the process of updating our main branches and they are currently rather stale. You might find it easier to use our docker container: `docker pull seahorn/seahorn-llvm10:nightly`. For build instructions, follow the build process in our docker container.

**Comment by naokikob** [comment]
Thanks. I could run SeaHorn using docker.
