### ISSUE TITLE
build problems

### ISSUE THREAD

**Issue by ffrohn** [seahorn/seahorn#197]
Hello,

I'm trying to build seahorn on an up-to-date Debian stable system. When I follow the build instructions, the step
`cmake --build .`
fails with the following error:

```
CMake Error at /home/ffrohn/repos/seahorn/build/z3-prefix/src/z3-stamp/z3-build-RelWithDebInfo.cmake:16 (message):
  Command failed: 2

   'make' '-j3' '-C' 'build'

  See also

    /home/ffrohn/repos/seahorn/build/z3-prefix/src/z3-stamp/z3-build-*.log


CMakeFiles/z3.dir/build.make:110: recipe for target 'z3-prefix/src/z3-stamp/z3-build' failed
make[2]: *** [z3-prefix/src/z3-stamp/z3-build] Error 1
CMakeFiles/Makefile2:358: recipe for target 'CMakeFiles/z3.dir/all' failed
make[1]: *** [CMakeFiles/z3.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2
```

I attached the log-files. Thanks for your help!

Best
Florian

[z3-build-err.log](https://github.com/seahorn/seahorn/files/3187578/z3-build-err.log)
[z3-build-out.log](https://github.com/seahorn/seahorn/files/3187579/z3-build-out.log)

**Comment by caballa** [comment]
The compilation of z3 is failing. From your logs
```
In file included from /usr/include/c++/6/algorithm:60:0,
                 from ../src/util/hash.h:22,
                 from ../src/util/hashtable.h:26,
                 from ../src/util/str_hashtable.h:24,
                 from ../src/util/debug.cpp:24:
/usr/include/c++/6/utility: In function ‘constexpr typename std::tuple_element<_Int, std::pair<_Tp1, _Tp2> >::type&& std::get(std::pair<_Tp1, _Tp2>&&)’:
/usr/include/c++/6/utility:208:57: error: no matching function for call to ‘move()’
     { return __pair_get<_Int>::__move_get(std::move(__in)); }
```
which compiler/version are you using?

Also, are you trying `master` branch? I strongly recommend to work on `deep-dev-5.0` which is our current development branch and it will become soon `master`.
Also, notice that you can try seahorn directly from docker (https://hub.docker.com/r/seahorn/seahorn-llvm5).

**Comment by ffrohn** [comment]
I'm using `gcc 6.3.0`. After switching to the `deep-dev-5.0` branch, the build works. Thanks! However, running `run/bin/sea term test.c` on a few test files always yields:
```
Traceback (most recent call last):
  File "run/bin/sea", line 72, in <module>
    sys.exit (main (sys.argv[1:]))
  File "run/bin/sea", line 52, in main
    return cmd.main (argv)
  File "/local/home/ffrohn/repos/seahorn/build/run/lib/seapy/sea/__init__.py", line 151, in main
    return self.run (args, extra)
  File "/local/home/ffrohn/repos/seahorn/build/run/lib/seapy/sea/__init__.py", line 181, in run
    return args.func (args, extra)
  File "/local/home/ffrohn/repos/seahorn/build/run/lib/seapy/sea/__init__.py", line 253, in run
    res = c.main (argv)
  File "/local/home/ffrohn/repos/seahorn/build/run/lib/seapy/sea/__init__.py", line 151, in main
    return self.run (args, extra)
  File "/local/home/ffrohn/repos/seahorn/build/run/lib/seapy/sea/commands.py", line 1304, in run
    raise IOError(str(e))
IOError: No module named z3
```
Do I need to set some environment variables?

**Comment by caballa** [comment]
The termination engine `term` is obsolete. 
Did you try, for instance, after building `make test-simple` ?

**Comment by ffrohn** [comment]
`make test-simple` fails with
```
/bin/sh: 1: LIT_COMMAND-NOTFOUND: not found
test/CMakeFiles/test-simple.dir/build.make:57: recipe for target 'test/CMakeFiles/test-simple' failed
make[3]: *** [test/CMakeFiles/test-simple] Error 127
CMakeFiles/Makefile2:3872: recipe for target 'test/CMakeFiles/test-simple.dir/all' failed
make[2]: *** [test/CMakeFiles/test-simple.dir/all] Error 2
CMakeFiles/Makefile2:3879: recipe for target 'test/CMakeFiles/test-simple.dir/rule' failed
make[1]: *** [test/CMakeFiles/test-simple.dir/rule] Error 2
Makefile:1356: recipe for target 'test-simple' failed
make: *** [test-simple] Error 2
```
Is there an alternative to `term` or is termination analysis no longer supported by SeaHorn?

**Comment by caballa** [comment]
You just need to install `lit`. 
We have in the README file the instructions. Basically, 

```
pip install lit OutputCheck
```

**Comment by caballa** [comment]
Sorry, the termination analysis hasn't been supported for long time.

**Comment by ffrohn** [comment]
Sorry, I overlooked this step in the installation instructions. Thank you very much for your help!
